// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64              `json:"id"`
	OwnerID   int64              `json:"owner_id"`
	Balance   float64            `json:"balance"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Entry struct {
	ID        int64              `json:"id"`
	AccountID pgtype.Int8        `json:"account_id"`
	Amount    float64            `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Transfer struct {
	ID            int64       `json:"id"`
	FromAccountID pgtype.Int8 `json:"from_account_id"`
	ToAccountID   pgtype.Int8 `json:"to_account_id"`
	// amount must be positive
	Amount    float64            `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                int64              `json:"id"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	Fullname          string             `json:"fullname"`
	HashedPassword    string             `json:"hashed_password"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
